# This is a generated file. Not intended for manual editing.
services:
  devopscalculator:
    build:
      context: "/Users/mazur/RiderProjects/DevOpsCalculator"
      dockerfile: "DevOpsCalculator/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/DevOpsCalculator.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "mm007mm/devopscalculator:dev"
    ports: []
    volumes:
    - "/Users/mazur/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/mazur/RiderProjects/DevOpsCalculator/DevOpsCalculator:/app:rw"
    - "/Users/mazur/RiderProjects/DevOpsCalculator:/src:rw"
    working_dir: "/app"
